# docker-compose
version: "2"
services:
  web:
    working_dir: /usr/src/app
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    image: "node:8.11.3-alpine"
    user: node
    command: "npm start"