# docker-compose
version: "1"
services:
	node: 
		image: "node:8.11.3-alpine"
		user: node
		working_dir: /usr/src/app
		environment:
      	- NODE_ENV=production
    	volumes:
      	- ./:/usr/src/app
    	expose:
      	- "3000"
    	command: "npm start"